### ISSUE TITLE
Improve npm package CI testing

### ISSUE THREAD

**Issue by ArnaudPel** [abolis-biotechnologies/plate-maker#6]
## Rationale
Currently, our CI pipeline proceeds as follows:
- build a `.tar` package using the `tar` command
- run tests on that `.tar` package
- forget about that package
- publish a different package on npm

Clearly, this presents the risk of pushing a broken archive file on npm, without any warning from our CI.

## Implementation
I (@ArnaudPel) believe we can leverage the `npm pack` command to get a testable package that, if not the exact same, will be much alike the one about to be published on npm, [as discussed in this article](https://medium.com/@vcarl/problems-with-npm-link-and-an-alternative-4dbdd3e66811).

Precisely, I surmise the first step of this endeavor is to replace [the following line](https://github.com/abolis-biotechnologies/plate-maker/blob/7e2e524d9f0a14d9e49c7096b93f2ba0a73a3f1f/travis/travis_package_lib.sh#L44) by `npm pack`. Then improvise as needed.

**Comment by Zahen** [comment]
Release on NPM via Travis is done.
